name: redlino
description: A new Flutter project.
publish_to: "none"
version: 0.0.14+15

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.2
  animations: ^2.0.0
  auto_size_text_pk: ^3.0.0
  cached_network_image: ^3.0.0
  characters: ^1.1.0
  cloud_firestore: ^2.3.0
  cloud_functions: ^3.0.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  fcm_config: ^3.0.7
  firebase_auth: ^3.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  firebase_storage: ^10.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_inapp_purchase: ^5.0.2
  flutter_local_notifications: ^6.1.1
  flutter_svg: ^0.22.0
  flutter_vibrate: ^1.1.0
  get: ^4.3.4
  google_fonts: ^2.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+3
  intl: ^0.17.0
  logger: ^1.0.0
  material_floating_search_bar: ^0.3.4
  numeral: ^1.2.4
  permission_handler: ^8.1.2
  reactive_date_time_picker: ^0.1.3
  reactive_forms: ^10.4.1
  reactive_touch_spin: ^0.2.0-nullsafety.1
  stacked: ^2.1.9
  stacked_firebase_auth: ^0.2.8
  stacked_hooks: ^0.2.1
  stacked_services: ^0.8.8
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  wakelock: ^0.5.3+1
  webview_flutter: ^2.0.10

dev_dependencies:
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.3
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/redlino-large.png"

flutter_native_splash:
  background_image: assets/splash-background.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
